version: '3'
services:
  database:
    image: 'postgres:12.4'
    container_name: database
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_DB=ogre'
      - 'POSTGRES_PASSWORD=postgres'
    restart: always
  server:
    build: server/
    container_name: server
    depends_on:
      - database
    ports:
      - "3000:3000"
    restart: always